### ISSUE TITLE
How to generate muliti-view images in Blender?

### ISSUE THREAD

**Issue by gaunzi** [rehg-lab/lowshot-shapebias#1]
Hi guys,

Thanks for sharing this interesting work.
May I know more detailed operations about generating multi-view images from 3D objects in Blender? Or could you offer the scripts of this generation procedure kindly?   My e-mail is **cgye19@fudan.edu.cn**. 

Thanks again!

**Comment by sstojanov** [comment]
Hi, 

Thank you for your interest! Blender 2.79 rendering code for multi-view images of 3D objects is available at our [3D object shape reconstruction repository](https://github.com/rehg-lab/3DShapeGen/tree/master/Rendering).

Please feel free to reach out directly/reopen this issue if you have further questions.

**Comment by gaunzi** [comment]
Hi Stefan,

Thank you very much for your help with rendering the multi-view images!
By the way, how could I sample points from objects' surface and output the point cloud file (.npy)?

**Comment by sstojanov** [comment]
Hi, 

Please look into the python trimesh package ([repo](https://github.com/mikedh/trimesh), [docs](https://trimsh.org/trimesh.html)) and specifically the [mesh surface sampling functions](https://trimsh.org/trimesh.sample.html). The documentation is generally very clear and useful.

Note: trimesh also allows for visualizing point clouds, so you can make sure you're getting the expected results.

**Comment by gaunzi** [comment]
Get it！Thanks a lot for your guidance!
