### ISSUE TITLE
example code for generating images/point-clouds from 3D models?

### ISSUE THREAD

**Issue by Tsingularity** [rehg-lab/lowshot-shapebias#2]
Hi, thanks for the great work and for sharing your code!

I am just wondering, if possible, and convenient for you, could you also release the code for generating 2D-images/points-clouds from 3D models? Or provide the example code for doing these things (for example, the code snapshot for one single 3D model with given camera view parameters)? I am trying to reproduce your dataset building pipeline but I am not sure whether I do it in the same way as your paper. So I think a code example would be really helpful for us to follow your work!

Thanks for the insightful paper and great dataset again!

**Comment by sstojanov** [comment]
Hi, 

Thank you for your interest! Blender 2.79 rendering code for multi-view images of 3D objects is available at our [3D object shape reconstruction repository](https://github.com/rehg-lab/3DShapeGen/tree/master/Rendering). The code available is for ShapeNet and ABC datasets, but it can be changed to work with other datasets of `.obj` files. For example, [this is the line](https://github.com/rehg-lab/3DShapeGen/blob/0ed50730bd2738b187d09d29813985321fe6be22/Rendering/ShapeNet/generate.py#L60) where objects are imported, this can be "swapped out" for different `.obj` files. 

For sampling point clouds please look into the python trimesh package ([repo](https://github.com/mikedh/trimesh), [docs](https://trimsh.org/trimesh.html)) and specifically the [mesh surface sampling functions](https://trimsh.org/trimesh.sample.html). The documentation is generally very clear and useful. [Trimesh points](https://trimsh.org/trimesh.points.html) can be used to generate visualizations of point clouds after sampling, and `.ply` files can be exported for visualization in Blender.

Please feel free to reach out directly/reopen this issue if you have further questions.
