### ISSUE TITLE
Conv4 file missing

### ISSUE THREAD

**Issue by sinhaharsh** [rehg-lab/lowshot-shapebias#3]
Hi, thanks for the great code and for sharing your dataset. It seems a file is missing. Can you please look into it?

```
File "github/lowshot-shapebias/lssb/nets/__init__.py", line 4, in <module>
    from .conv4 import Conv4 as conv4
ModuleNotFoundError: No module named 'lssb.nets.conv4'
```

**Comment by sstojanov** [comment]
Hi, thank you for bringing this up! There must have been some issues with commits, the file has now been added.
