### ISSUE TITLE
How to pre-train DGCNN

### ISSUE THREAD

**Issue by LexieYang** [rehg-lab/lowshot-shapebias#5]
Hi @sstojanov ,

May I know how to pre-train DGCNN? It is hard for me to find the correct .sh and .py files to get DGCNN pretrained. Besides, may I know whether you pre-train DGCNN on all training classes in a traditional way or in a few-shot meta-learning way? Thanks in advance.

Minmin

**Comment by sstojanov** [comment]
Hi Minmin,

Thank you for your question. The DGCNN is trained as a classifier with cross entropy on the base classes, as in the [SimpleShot paper](https://arxiv.org/abs/1911.04623). Have tried using the following bash script to train dgcnn [training_scripts/train_dgcnn_simpleshot.sh](https://github.com/rehg-lab/lowshot-shapebias/tree/main/training_scripts/train_dgcnn_simpleshot.sh)?

Stefan

**Comment by sstojanov** [comment]
Closing this issue for now as it's been 2 months. Please reopen it if the issue persists.
