### ISSUE TITLE
How can I also extract surface normals in your code.

### ISSUE THREAD

**Issue by miangoleh** [rehg-lab/lowshot-shapebias#7]

**Comment by sstojanov** [comment]
Hi, thanks for your interest! Can you please provide a bit more detail about what you need?

Thanks!

**Comment by miangoleh** [comment]
Your code exports segmentations and depth (z-buffer) for each view as well as the rendered image. I was wondering if we can export the surface normal maps as well.

**Comment by sstojanov** [comment]
If you'd like to render normals using blender, please refer to our other project.

 https://github.com/rehg-lab/3DShapeGen/tree/master/Rendering

Which can render normals for Blender 2.79b. Toys4K require Blender 2.8 and above, but it should be possible to get it to work using this original code as reference. We didn't implement normals rendering for this project.

**Comment by miangoleh** [comment]
Thanks for your quick reply. I will take a look and post an issue on the other repo if I encounter a problem.
